default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cat_development

test:
  <<: *default
  database: cat_test

production:
  <<: *default
  database: cat_production
  username: cat
  password: <%= ENV['CAT_DATABASE_PASSWORD'] %>
